# 
# Definition of all trackable objects
# Identifier corresponds to User Data set in Motive
#
rigid_bodies:
    '11':
        pose: calibration_tool_station1/pose
        pose2d: calibration_tool_station1/ground_pose
        child_frame_id: calibration_tool_station1
        parent_frame_id: optitrack_frame
    '12':
        pose: optitrack_robot_station1/pose
        pose2d: optitrack_robot_station1/ground_pose
        child_frame_id: robot_station1
        parent_frame_id: optitrack_frame
    '21':
        pose: calibration_tool_station2/pose
        pose2d: calibration_tool_station2/ground_pose
        child_frame_id: calibration_tool_station2
        parent_frame_id: optitrack_frame
    '22':
        pose: optitrack_robot_station2/pose
        pose2d: optitrack_robot_station2/ground_pose
        child_frame_id: robot_station2
        parent_frame_id: optitrack_frame
