# 
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: calibration_tool/pose
        pose2d: calibration_tool/ground_pose
        child_frame_id: calibration_tool
        parent_frame_id: optitrack_frame
    '2':
        pose: calibration_tool/robot_pose
        pose2d: calibration_tool/robot_ground_pose
        child_frame_id: robot
        parent_frame_id: optitrack_frame

